Added guide for GPU on WSL2
tensorflow/build pull request #19
Opened 2020-12-27 13:51 UTC by Avditvs

Added guide for GPU usage in Windows Subsystem For Linux

2021-01-05 19:52 UTC, angerson requested changes
Very nice! Thank you for adding this!

Once the formatting has been adjusted I'll approve and merge!

2021-01-05 19:52 UTC, angerson commented on wsl2_gpu_guide/README.md
> +# WSL2 gpu guide
Can you change this to match up with the README? That is, the README should also say "WSL2 GPU Guide" (the directory name) and the short description should be the same as well. The [example](https://github.com/tensorflow/build/tree/master/directory_template) includes all that too -- the long description will fit under the section separator (`***`)

2021-01-05 19:52 UTC, angerson commented on wsl2_gpu_guide/README.md
> +Maintainer: @Avditvs (Independant)
Minor typo: "independent"

2021-01-16 17:26 UTC, Avditvs commented
@angerson The changes have been applied.

2021-01-19 18:07 UTC, angerson approved these changes
Thanks!

2021-01-19 18:07 UTC, merged